# Generated by Django 3.1.3 on 2024-06-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detalle',
            new_name='Detalle_Venta',
        ),
    ]
